---
- name: "Update the kernel"
  yum: name=kernel state=latest
  register: kernel

- name: upgrade all packages
  yum: name=* state=latest

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true
  when: kernel

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  sudo: false
  when: kernel



- name: install RPM packages
  tags: packages
  yum: name={{ item }} state=present
  with_items: base_packages

- name: install latest RPM packages
  tags: packages
  yum: name={{ item }} state=latest
  with_items: latest_packages

