---
- name: upgrade all packages
  yum: name=* state=latest

- name: install RPM packages
  tags: packages
  yum: name={{ item }} state=present
  with_items: base_packages

- name: install latest RPM packages
  tags: packages
  yum: name={{ item }} state=latest
  with_items: latest_packages

