- name: Generate the root password for ldap
  shell: slappasswd -s {{ openldap_server_rootpw }} 
  tags: ldap_server
  register: root_password

- name: install  /etc/openldap/slapd.d/cn=config/olcDatabase={2}bdb.ldif
  tags: ldap_server
  template: src=etc/openldap/slapd.d/cn=config/olcDatabase={2}bdb.ldif.j2 dest=/etc/openldap/slapd.d/cn=config/olcDatabase={2}bdb.ldif owner=ldap group=ldap mode=0664  backup=yes

- name: install  /etc/openldap/slapd.d/cn=config/olcDatabase={1}monitor.ldif
  tags: ldap_server
  template: src=etc/openldap/slapd.d/cn=config/olcDatabase={1}monitor.ldif.j2 dest=/etc/openldap/slapd.d/cn=config/olcDatabase={1}monitor.ldif owner=ldap group=ldap mode=0664  backup=yes

- service: name=slapd state=started enabled=yes
