---
- name: install CentOS nmon package
  tags: nmon
  yum: name={{ item }} state=present
  with_items: nmon_centos_packages
  when: nmon_centos_packages is defined

- name: Creates nmon log dir
  tags: nmon
  file: path={{nmon_log}} state=directory owner=root group=root mode=0755

- name: Creates local script dir
  tags: nmon
  file: path={{nmon_install}} state=directory owner=root group=root mode=0700

# -ft spreadsheet output format and includes top processes, -s frequency in seconds -c count -m location_to_save
- cron: name="nmon" hour=0 minute=0
        user="root" job="{{nmon_install}}/nmon.sh"
        cron_file=nmon
  tags: nmon

- cron: name="nmon_reboot"
        user="root" special_time=reboot job="{{nmon_install}}/nmon.sh"
        cron_file=nmon.reboot
  tags: nmon

- name: nmon logrotate
  template: src=etc/logrotate.d/nmon.j2 dest=/etc/logrotate.d/nmon owner=root group=root mode=0444
  tags: nmon

- name: nmon script
  template: src=usr/share/nmon/nmon.j2 dest="{{nmon_install}}/nmon.sh" owner=root group=root mode=0554
  tags: nmon
