- name: install  nslcd config
  tags: ldap_client
  template: src=etc/nslcd.conf.j2 dest=/etc/nslcd.conf owner=root group=root mode=0400  backup=yes

- name: install  ldap config
  tags: ldap_client  
  template: src=etc/openldap/ldap.conf.j2 dest=/etc/openldap/ldap.conf owner=root group=root mode=0400  backup=yes

- command:  authconfig --enablemkhomedir --update

- service: name=nslcd state=restarted

- service: name=nscd state=restarted

