---
- name: upgrade all packages
  yum: name=* state=latest

- name: install CentOS packages for cobbler server
  tags: cobbler
  yum: name={{ item }} state=present
  with_items: cobbler_centos_packages
  when: cobbler_centos_packages is defined

- name: turn on cobblerd service 
  service: name=cobblerd enabled=yes
  notify: restart cobblerd

- name: turn on dhcpd service
  service: name=dhcpd enabled=yes
  notify: restart dhcpd

- name: turn on named service
  service: name=named enabled=yes
  notify: restart named

- name: template /etc/cobbler/settings.
  template: src=etc/cobbler/service_{{ ansible_distribution }}.conf.j2 dest=/etc/cobbler/serttings owner=root group=root mode=0444
  notify: restart gmond

