---
- name: upgrade all packages
  yum: name=* state=latest

- name: install CentOS packages for cobbler server
  yum: name={{ item }} state=present
  with_items: cobbler_centos_packages
  when: cobbler_centos_packages is defined

- name: template /etc/cobbler/settings
  template: src=etc/cobbler/settings_{{ ansible_distribution }}.conf.j2 dest=/etc/cobbler/settings owner=root group=root mode=0444

- name: template /etc/cobbler/dhcp.template
  template: src=etc/cobbler/dhcp.template_{{ ansible_distribution }}.conf.j2 dest=/etc/cobbler/dhcp.template owner=root group=root mode=0444

- name: template /etc/cobbler/named.template
  template: src=etc/cobbler/named.template_{{ ansible_distribution }}.conf.j2 dest=/etc/cobbler/named.template owner=root group=root mode=0444

- name: template /etc/cobbler/zone.template
  template: src=etc/cobbler/zone.template_{{ ansible_distribution }}.conf.j2 dest=/etc/cobbler/zone.template owner=root group=root mode=0444


- name: template /etc/xinetd.d/tftp
  template: src=etc/xinetd.d/tftp.template_{{ ansible_distribution }}.conf.j2 dest=/etc/xinetd.d/tftp.template owner=root group=root mode=0444

- name: Enable services
  service: name={{item}} state=started enabled=yes
  with_items:
    - xinetd
    - httpd
    - cobblerd

## cobbbler sync is failing as cobblerd is taking time to start service  ; adding pause for that reason
- pause: seconds=5

- name: cobbler sync
  command: cobbler sync 
