---
- name: install CentOS packages for ganglia nodes
  tags: ganglia-client
  yum: name={{ item }} state=present
  with_items: ganglia_centos_packages
  when: ganglia_centos_packages is defined

- name: install latest CentOS packages for ganglia nodes
  tags: ganglia-client
  yum: name={{ item }} state=latest
  with_items: ganglia_centos_latest_packages
  when: ganglia_centos_latest_packages is defined

- name: template /etc/ganglia/gmond.conf
  tags: ganglia-client
  template: src=etc/ganglia/gmond_{{ ansible_distribution }}.conf.j2 dest=/etc/ganglia/gmond.conf owner=root group=root mode=0444
  notify: restart gmond

- name: enable gmond
  tags: ganglia-client
  service: name=gmond state=started enabled=yes

