- name: install  /etc/ssh/ssh_config
  tags: ssh_config
  template: src=etc/ssh/sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0444 backup=yes 
- service: name=sshd state=reloaded

